- hosts: eks_clusters
  gather_facts: false

  vars:
    dex_chain_namespace: saga-{{ dex_chain_id | replace('_', '-') }}
    dex_service_namespace: "{{ 'sagasrv-dex' if dex_explorer_enabled else undefined }}"

  tasks:
    - name: Fail if dex_explorer_enabled is false or undefined
      ansible.builtin.fail:
        msg: "dex_explorer_enabled must be true to deploy dex explorer services"
      when: not dex_explorer_enabled | default(false) | bool

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: ~/.ansible/deployments/{{ eks_cluster_name }}/lil
        state: directory
        mode: '0744'

    - name: Generate Dex Explorer specs
      ansible.builtin.template:
        src: config/dex-explorer.yml.j2
        dest: ~/.ansible/deployments/{{ eks_cluster_name }}/lil/dex-explorer.yml
        mode: '0644'
      vars:
        rpc_url_suffixes: "{{ [rpc_generic_url_suffix, url_suffix] if rpc_generic_url_suffix is defined else [url_suffix] }}"

    - name: Deploy Dex Explorer services
      kubernetes.core.k8s:
        state: present
        src: ~/.ansible/deployments/{{ eks_cluster_name }}/lil/dex-explorer.yml
