- hosts: eks_clusters
  gather_facts: false

  vars:
    dex_chain_namespace: saga-{{ dex_chain_id | replace('_', '-') }}
    dex_vanity_name: "{{ dex_chain_id.split('_')[0] }}"
    dex_balance_monitor_enabled: dex_feepayers_monitor_targets is defined
    dex_service_namespace: "{{ 'sagasrv-dex' if dex_balance_monitor_enabled else undefined }}"

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: ~/.ansible/deployments/{{ eks_cluster_name }}/lil
        state: directory
        mode: '0744'

    - name: Generate Dex Sidecar spec
      ansible.builtin.template:
        src: config/dex-sidecar.yml.j2
        dest: ~/.ansible/deployments/{{ eks_cluster_name }}/lil/dex-sidecar.yml
        mode: '0644'

    - name: Generate Cosmos Balance Exporter specs
      ansible.builtin.template:
        src: config/cosmos-balance-exporter.yml.j2
        dest: ~/.ansible/deployments/{{ eks_cluster_name }}/lil/cosmos-balance-exporter.yml
        mode: '0644'
      when: dex_feepayers_monitor_targets is defined
