apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blockscout-rules
  namespace: sagasrv-metrics
spec:
  groups:
  - name: blockscout-group
    rules:
    - alert: BlockscoutIndexingFallingBehind
      annotations:
        description: Indexer is *{{ $value }}* blocks behind (or metrics missing) for ≥20m.
        summary: Indexing is behind on *{{ $labels.chainId }}*
      expr: |
        clamp_min(
          sum by (chainId) (
            max_over_time(cometbft_consensus_height[20m])
          )
          -
          sum by (chainId) (
            max_over_time(blockscout_total_blocks[20m])
          ),
          0
        ) > 1000
        OR absent(blockscout_total_blocks) OR absent(cometbft_consensus_height)
      for: 20m
      labels:
        severity: warning
