apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: saga-chainlet-rules
  namespace: sagasrv-metrics
spec:
  groups:
  - name: chainlet-group
    rules:
    - alert: ChainletJailedValidator
      annotations:
        summary: Validator(s) jailed: *{{ $labels.moniker }}*
        description: *{{ $labels.moniker }}* on *{{ $labels.chainId }}* has been jailed (or metric missing) for ≥15m.
      expr: |
        sum without (address, app, instance, job) (
          max_over_time(cosmos_validators_jailed{app="cosmos-exporter"}[15m])
        ) > 0
        OR absent(cosmos_validators_jailed{app="cosmos-exporter"})
      for: 15m
      labels:
        severity: warning
    - alert: ChainletByzantineValidator
      annotations:
        description: Byzantine validator(s) on *{{ $labels.chainId }}* ({{ $value }})
        summary: Byzantine validator
      expr: |
        sum without(app, instance, job, chainId) (
          max_over_time(cometbft_consensus_byzantine_validators{app="chainlet"}[15m])
        ) > 0
        OR absent(cometbft_consensus_byzantine_validators{app="chainlet"})
      for: 15m
      labels:
        severity: critical
    - alert: ChainletMissedBlocksWarning
      annotations:
        description: "*{{ $labels.moniker }}* missed *{{ $value }}* blocks on *{{ $labels.chainId }}* in 5 minutes"
        summary: Missed more than 10 blocks in 5m
      expr: |
        sum without (address, app, instance, job)(
          clamp_min(
            increase(cosmos_validators_missed_blocks{app="cosmos-exporter"}[5m]), 0
          )
        ) > 10
        OR absent(cosmos_validators_missed_blocks{app="cosmos-exporter"})
      labels:
        severity: warning
      for: 5m
    - alert: ChainletMissedBlocks
      annotations:
        description: "*{{ $labels.moniker }}* missed *{{ $value }}* blocks on *{{ $labels.chainId }}* in 15 minutes"
        summary: Missed more than 50 blocks in 15m
      expr: |
        sum without (address, app, instance, job)(
          clamp_min(
            increase(cosmos_validators_missed_blocks{app="cosmos-exporter"}[15m]), 0
          )
        ) > 50
        OR absent(cosmos_validators_missed_blocks{app="cosmos-exporter"})
      labels:
        severity: critical
      for: 15m
    - alert: ChainletNotProducingBlocksWarning
      annotations:
        description: "*{{ $labels.chainId }}* didn't produced blocks in the last 5 minutes"
        summary: No blocks produced in the last 5 minutes
      expr: |
        (
          sum without(app, instance, job, chainId) (
            increase(cometbft_consensus_height{app="chainlet"}[5m])
          ) == 0
        )
        OR absent(cometbft_consensus_height{app="chainlet"})
      labels:
        severity: warning
      for: 5m
    - alert: ChainletNotProducingBlocks
      annotations:
        description: "*{{ $labels.chainId }}* didn't produced blocks in the last 15 minutes"
        summary: No blocks produced in the last 15 minutes
      expr: |
        (
          sum without(app, instance, job, chainId) (
            increase(cometbft_consensus_height{app="chainlet"}[15m])
          ) == 0
        )
        OR absent(cometbft_consensus_height{app="chainlet"})
      labels:
        severity: critical
      for: 15m
    - alert: ChainletAverageBlockTimeTooLong
      annotations:
        description: Average block time for *{{ $labels.chainId }}* is *{{ $value }}* seconds
        summary: Average block time too long
      expr: |
        avg by (chainId) (
          avg_over_time(blockscout_average_block_time[5m])
        ) / 1000 > 20
        OR absent(blockscout_average_block_time)
      for: 5m
      labels:
        severity: warning
    - alert: ChainletMempoolTooBig
      annotations:
        description: Mempool for *{{ $labels.chainId }}* is *{{ $value }}*
        summary: Mempool bigger than 300
      expr: |
        sum without(app, instance, job, chainId) (
          max_over_time(
            cometbft_mempool_size{app="chainlet"}[15m]
          )
          > 300
        )
        OR absent(cometbft_mempool_size{app="chainlet"})
      labels:
        severity: critical
      for: 15m
