apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dex-rules
  namespace: sagasrv-metrics
spec:
  groups:
  - name: dex-group
    rules:
    - alert: DexFeepayerBalanceLow
      annotations:
        description: Dex feepayer balance < 1000gas (*{{ $labels.account_name }} - {{ $labels.address }}*)
        summary: Low dex feepayer balance
      expr: sum(cosmos_balance{chain_id="sagaevm-5464-1"}) by (account_name, address) / 1000000000000000000 < 1000
      labels:
        severity: warning
    - alert: SscRelayerBalanceLow
      annotations:
        description: Relayer balance < 3 on SSC-1 (*{{ $labels.address_label }} - {{ $labels.address }}*)
        summary: Critically low ssc relayer balance
      expr: sum(cosmos_balance{chain_id="ssc-1"}) by (account_name, address) / 1000000 < 3
      labels:
        severity: warning