apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dex-rules
  namespace: sagasrv-metrics
spec:
  groups:
  - name: dex-group
    rules:
    - alert: DexFeepayerBalanceLow
      annotations:
        description: Dex feepayer balance < 1000 (*{{ $labels.address_label }} - {{ $labels.address }}*)
        summary: Low dex feepayer balance
      expr: sum(evm_balance{}) by (address_label, address) < 1000
      labels:
        severity: warning
    - alert: DexFeepayerBalanceCritiallyLow
      annotations:
        description: Dex feepayer balance < 10 (*{{ $labels.address_label }} - {{ $labels.address }}*)
        summary: Critically low dex feepayer balance
      expr: sum(evm_balance{}) by (address_label, address) < 10
      labels:
        severity: critical