apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ingress-rules
  namespace: sagasrv-metrics
spec:
  groups:
  - name: ingress-group
    rules:
    - alert: IngressLowSuccessRate
      annotations:
        description: Http success rate for {{ $labels.host }} is {{ $value }}%
        summary: Http success rate (non 4|5xx return) below 95%
      expr: sum(rate(nginx_ingress_controller_requests{controller_pod=~".*",controller_class=~".*",namespace=~".*",ingress=~".*",status!~"[4-5].*"}[2m])) by (host) / sum(rate(nginx_ingress_controller_requests{controller_pod=~".*",controller_class=~".*",namespace=~".*",ingress=~".*"}[2m])) by (host) * 100 < 95
      labels:
        severity: warning