apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: spc-rules
  namespace: sagasrv-metrics
spec:
  groups:
  - name: spc-group
    rules:
    - alert: SpcJailedValidator
      expr: |
        sum without (address, app, instance, job) (
          max_over_time(cosmos_validators_jailed{app="spc-cosmos-exporter"}[15m])
        ) > 0
        OR absent(cosmos_validators_jailed{app="spc-cosmos-exporter"})
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "Validator(s) jailed: *{{ $labels.moniker }}*"
        description: "*{{ $labels.moniker }}* has been jailed (or metric missing) for ≥15m."
    - alert: SpcByzantineValidator
      expr: |
        sum without(instance, job) (
          max_over_time(cometbft_consensus_byzantine_validators{app="spc"}[15m])
        ) > 0
        OR absent(cometbft_consensus_byzantine_validators{app="spc"})
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "Byzantine validator(s) detected"
        description: "At least one validator reported as byzantine in the last 15 minutes (or metric missing). Count: {{$value}}"
    - alert: SpcMissedBlocksWarning
      expr: |
        sum without (address, app, instance, job)(
          clamp_min(
            increase(cosmos_validators_missed_blocks{app="spc-cosmos-exporter"}[5m]), 0
          )
        ) > 10
        OR absent(cosmos_validators_missed_blocks{app="spc-cosmos-exporter"})
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "{{$labels.moniker}} missed >10 blocks in 5m"
        description: "Validator {{$labels.moniker}} missed {{$value}} blocks over 5 minutes (or metric missing)."
    - alert: SpcMissedBlocks
      expr: |
        sum without (address, app, instance, job)(
          clamp_min(
            increase(cosmos_validators_missed_blocks{app="spc-cosmos-exporter"}[15m]), 0
          )
        ) > 50
        OR absent(cosmos_validators_missed_blocks{app="spc-cosmos-exporter"})
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "{{$labels.moniker}} missed a high number of blocks"
        description: "Validator {{$labels.moniker}} missed {{$value}} blocks in 15 minutes (or metric missing)."
    - alert: SpcNotProducingBlocksWarning
      expr: |
        (
          sum without(instance, job) (
            increase(cometbft_consensus_height{app="spc"}[5m])
          ) == 0
        )
        OR absent(cometbft_consensus_height{app="spc"})
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "SPC has not produced blocks for ≥5 minutes"
        description: "No increase in cometbft_consensus_height over the last 5m (or the metric is missing)."
    - alert: SpcNotProducingBlocks
      expr: |
        (
          sum without(instance, job) (
            increase(cometbft_consensus_height{app="spc"}[15m])
          ) == 0
        )
        OR absent(cometbft_consensus_height{app="spc"})
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "SPC has not produced blocks for ≥15 minutes"
        description: "No increase in cometbft_consensus_height over the last 15m (or the metric is missing)."
    - alert: SpcMempoolTooBig
      expr: |
        (
          max_over_time(
            cometbft_mempool_size{app="spc"}[15m]
          )
          > 300
        )
        OR absent(cometbft_mempool_size{app="spc"})
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "SPC mempool critically large on {{$labels.instance}}"
        description: "Mempool stuck above 300 tx for ≥15m (or metric missing). Current: {{$value}}."