{
 "title": "Blockscout / Stats",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(blockscout_total_transactions) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(blockscout_total_blocks) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total addresses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(blockscout_total_addresses) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total transactions today",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(blockscout_total_transactions_today) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network utilization percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(blockscout_network_utilization_percentage) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average block time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(blockscout_average_block_time) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas price (slow)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_slow) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas used today",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_used_today) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas price (fast)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_fast) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas price (average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_average) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks behind",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(cometbft_consensus_height) by (chainId) - sum(blockscout_total_blocks) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}