{
 "title": "Blockscout / Application Total",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pending Block Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pending_block_operations_count{app=\"blockscout-indexer\"}",
     "legendFormat": "{{chainId}}"
    }
   ]
  },
  {
   "title": "Import Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "import_errors_count{app=\"blockscout-indexer\"}",
     "legendFormat": "{{chainId}}"
    }
   ]
  },
  {
   "title": "Missing Blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "missing_block_count{app=\"blockscout-indexer\"}",
     "legendFormat": "{{chainId}}"
    }
   ]
  },
  {
   "title": "Delay from last node block",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(delay_from_last_node_block{app=\"blockscout-indexer\"}) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(process_threads_total{app=\"blockscout-indexer\"}) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{app=\"blockscout-indexer\"}) by (chainId)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}