{
 "title": "Blockscout / Stats by Chainlets",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "chain_id", "label": "Chain Id", "query": { "query": "label_values(chain_id)" } }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Indexing %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_total_blocks{chainId=~\"$chain_id\"}) / sum(cometbft_consensus_height{chainId=~\"$chain_id\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cometbft_consensus_height{chainId=~\"$chain_id\"}) - sum(blockscout_total_blocks{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_total_blocks{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_total_transactions{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Addresses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_total_addresses{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Block Time (ms)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_average_block_time{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Today Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_total_transactions_today{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Utilization %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_network_utilization_percentage{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Gas Used Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_gas_used_today{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Gas Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_average{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Gas Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_slow{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fast Gas Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_fast{chainId=~\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(blockscout_total_transactions{chainId=~\"$chain_id\"})",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "title": "Total blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(blockscout_total_blocks{chainId=~\"$chain_id\"})",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Total addresses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(blockscout_total_addresses{chainId=~\"$chain_id\"})",
     "legendFormat": "addresses"
    }
   ]
  },
  {
   "title": "Total transactions today",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(blockscout_total_transactions_today{chainId=~\"$chain_id\"})",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "title": "Network utilization percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(blockscout_network_utilization_percentage{chainId=~\"$chain_id\"})",
     "legendFormat": "utilization_percentage"
    }
   ]
  },
  {
   "title": "Average block time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(blockscout_average_block_time{chainId=~\"$chain_id\"})",
     "legendFormat": "block_time"
    }
   ]
  },
  {
   "title": "Gas used today",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_used_today{chainId=~\"$chain_id\"})",
     "legendFormat": "gas_used"
    }
   ]
  },
  {
   "title": "Gas price (average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_average{chainId=~\"$chain_id\"})",
     "legendFormat": "gas_price"
    }
   ]
  },
  {
   "title": "Gas price (slow)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_slow{chainId=~\"$chain_id\"})",
     "legendFormat": "gas_price"
    }
   ]
  },
  {
   "title": "Gas price (fast)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(blockscout_gas_prices_fast{chainId=~\"$chain_id\"})",
     "legendFormat": "gas_price"
    }
   ]
  },
  {
   "title": "Blocks behind",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(cometbft_consensus_height{chainId=~\"$chain_id\"}) - sum(blockscout_total_blocks{chainId=~\"$chain_id\"})",
     "legendFormat": "blocks_behind"
    }
   ]
  },
  {
   "title": "Indexing percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(blockscout_total_blocks{chainId=~\"$chain_id\"}) / sum(cometbft_consensus_height{chainId=~\"$chain_id\"}) * 100",
     "legendFormat": "indexing_percentage"
    }
   ]
  }
 ]
}