{
 "title": "Blockscout / BEAM by Chainlet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chainId",
    "label": "ChainId",
    "query": {
     "query": "label_values(erlang_vm_process_count, chainId)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "ETS/DETS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_ets_limit{chainId=\"$chainId\"}",
     "legendFormat": "ETS Limit"
    },
    {
     "expr": "erlang_vm_ets_tables{chainId=\"$chainId\"}",
     "legendFormat": "ETS Tables"
    },
    {
     "expr": "erlang_vm_dets_tables{chainId=\"$chainId\"}",
     "legendFormat": "DETS Tables"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{chainId=\"$chainId\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{chainId=\"$chainId\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{chainId=\"$chainId\"}[$interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{chainId=\"$chainId\"}[$interval])",
     "legendFormat": "Reductions"
    },
    {
     "expr": "irate(erlang_vm_statistics_runtime_milliseconds{chainId=\"$chainId\"}[$interval])",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{chainId=\"$chainId\"}"
    }
   ]
  },
  {
   "title": "VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{chainId=\"$chainId\"}[$interval])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{chainId=\"$chainId\"}[$interval])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{chainId=\"$chainId\"}[$interval])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{chainId=\"$chainId\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{chainId=\"$chainId\", kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=\"$chainId\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=\"$chainId\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=\"$chainId\", usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=\"$chainId\", usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "OS Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{chainId=\"$chainId\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{chainId=\"$chainId\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "File Descriptors & Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{chainId=\"$chainId\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{chainId=\"$chainId\"}",
     "legendFormat": "Max FDs"
    },
    {
     "expr": "erlang_vm_port_limit{chainId=\"$chainId\"}",
     "legendFormat": "Max Ports"
    },
    {
     "expr": "erlang_vm_port_count{chainId=\"$chainId\"}",
     "legendFormat": "Ports"
    }
   ]
  },
  {
   "title": "Native Threads & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_threads_total{chainId=\"$chainId\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{chainId=\"$chainId\"}[$interval])) without (kind) * 100",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}