{
 "title": "Blockscout / Elixir APP by Chainlet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chainId",
    "label": "ChainId",
    "query": {
     "query": "label_values(erlang_vm_process_count, chainId)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP request time, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{chainId=~\"$chainId\"}[$interval])) by(status_class) / sum(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\"}[$interval])) by(status_class)",
     "legendFormat": "{{status_class}}"
    }
   ]
  },
  {
   "title": "Controller call durations, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(phoenix_controller_call_duration_microseconds_sum{chainId=~\"$chainId\"}[$interval]) / rate(phoenix_controller_call_duration_microseconds_count{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "HTTP request count, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "{{method}} {{request_path}}"
    }
   ]
  },
  {
   "title": "Ecto Query Duration, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(ecto_query_duration_microseconds_sum{chainId=~\"$chainId\"}[$interval]) / rate(ecto_query_duration_microseconds_count{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "Ecto query"
    }
   ]
  },
  {
   "title": "Ecto, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(ecto_decode_duration_microseconds_sum{chainId=~\"$chainId\"}[$interval]) / rate(ecto_decode_duration_microseconds_count{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "The time spent decoding the result, $interval average"
    },
    {
     "expr": "rate(ecto_queue_duration_microseconds_sum{chainId=~\"$chainId\"}[$interval]) / rate(ecto_queue_duration_microseconds_count{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "The time spent to check the connection out, $interval average"
    }
   ]
  },
  {
   "title": "View rendering time, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(phoenix_controller_render_duration_microseconds_sum{chainId=~\"$chainId\"}[$interval]) / rate(phoenix_controller_render_duration_microseconds_count{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Plug scrape duration, $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(telemetry_scrape_duration_seconds_sum{chainId=~\"$chainId\"}[$interval]) / rate(telemetry_scrape_duration_seconds_count{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "Scrape duration"
    }
   ]
  },
  {
   "title": "Plug scrape size (uncompressed), $interval average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(telemetry_scrape_size_bytes_sum{chainId=~\"$chainId\"}[$interval]) / rate(telemetry_scrape_size_bytes_count{chainId=~\"$chainId\"}[$interval])",
     "legendFormat": "Scrape duration"
    }
   ]
  }
 ]
}