{
 "title": "Blockscout / Elli by Chainlet",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chainId",
    "label": "ChainId",
    "query": {
     "query": "label_values(process_uptime_seconds, chainId)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(process_uptime_seconds, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{chainId=\"ailandtestnet_1699217576328100-1\", app=\"$app\"}",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{chainId=~\"$chainId\", app=\"$app\"}[30s])) without (kind) * 100"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{chainId=~\"$chainId\", app=\"$app\"}[30s]))/sum(rate(http_request_duration_microseconds_count{chainId=~\"$chainId\"}[30s]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{chainId=~\"$chainId\", app=\"$app\"}[30s])) + sum(irate(http_requests_failed_total{chainId=~\"$chainId\", app=\"$app\"}[30s]))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{chainId=~\"$chainId\", status_class=\"informational\"}[5m]))/sum(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"informational\"}[5m]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{chainId=~\"$chainId\", status_class=\"success\"}[5m]))/sum(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"success\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{chainId=~\"$chainId\", status_class=\"redirection\"}[5m]))/sum(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"redirection\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{chainId=~\"$chainId\", status_class=\"client-error\"}[5m]))/sum(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"client-error\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{chainId=~\"$chainId\", status_class=\"server-error\"}[5m]))/sum(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"server-error\"}[5m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{chainId=~\"$chainId\", status_class=\"unknown\"}[5m]))/sum(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"unknown\"}[5m]))",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"informational\"}[1m]))"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"success\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"redirection\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"client-error\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"server-error\"}[1m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{chainId=~\"$chainId\", status_class=\"unknown\"}[1m]))",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum by (reason)(irate(http_requests_failed_total{chainId=~\"$chainId\", reason=\"request_closed\"}[1m]))",
     "legendFormat": "closed"
    },
    {
     "expr": "sum by (reason)(irate(http_requests_failed_total{chainId=~\"$chainId\", reason=\"timeout\"}[1m]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_process_count{chainId=~\"$chainId\", app=\"$app\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{chainId=~\"$chainId\", app=\"$app\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{chainId=~\"$chainId\", app=\"$app\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{chainId=~\"$chainId\", app=\"$app\"}[5m])",
     "legendFormat": "Reductions"
    }
   ]
  },
  {
   "title": "VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{chainId=~\"$chainId\", app=\"$app\"}[5m])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{chainId=~\"$chainId\", app=\"$app\"}[5m])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{chainId=~\"$chainId\", app=\"$app\"}[5m])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{chainId=~\"$chainId\", app=\"$app\"}[5m])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{chainId=~\"$chainId\", kind=\"processes\", app=\"$app\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=~\"$chainId\", usage=\"atom\", app=\"$app\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=~\"$chainId\", usage=\"binary\", app=\"$app\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=~\"$chainId\", usage=\"code\", app=\"$app\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{chainId=~\"$chainId\", usage=\"ets\", app=\"$app\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "OS Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{chainId=~\"$chainId\", app=\"$app\"}",
     "legendFormat": "Vertual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{chainId=~\"$chainId\", app=\"$app\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "File Descriptors & Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{chainId=~\"$chainId\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{chainId=~\"$chainId\"}",
     "legendFormat": "Max FDs"
    },
    {
     "expr": "erlang_vm_port_limit{chainId=~\"$chainId\"}",
     "legendFormat": "Max Ports"
    },
    {
     "expr": "erlang_vm_port_count{chainId=~\"$chainId\"}",
     "legendFormat": "Ports"
    }
   ]
  },
  {
   "title": "Native Threads & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_threads_total{chainId=~\"$chainId\", app=\"$app\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{chainId=~\"$chainId\", app=\"$app\"}[30s])) without (kind) * 100",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}