{
 "title": "Controller Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Deployed chains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "controller_deployer_deployed_chains{app=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running chains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "controller_deployer_running_chains{app=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing chains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "controller_deployer_processing_chains{app=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online chains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "controller_sources_online_chains{app=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of syncing with the deployer errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "controller_deployer_sync_errors{app=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of syncing with chain sources errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "controller_sources_sync_errors{app=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deploy errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "controller_deployer_deploy_errors{app=\"controller\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}