{
 "title": "Ethproxy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ethproxy_rpc_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(ethproxy_rpc_requests_total[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "sum(ethproxy_rpc_errors_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests error percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(ethproxy_rpc_errors_total[1m])) / sum(rate(ethproxy_rpc_requests_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(ethproxy_rpc_errors_total[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second by cause",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(ethproxy_rpc_errors_total[1m])) by (message)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests error percentage by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(ethproxy_rpc_errors_total[1m])) by (method) / sum(rate(ethproxy_rpc_requests_total[1m])) by (method) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Rate Limit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total rate limited requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "sum(ethproxy_rate_limit_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rate limited requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(ethproxy_rate_limit_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Latency distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(ethproxy_rpc_duration_seconds_bucket{}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency distribution sendRawTransaction",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(ethproxy_rpc_duration_seconds_bucket{method=\"eth_sendRawTransaction\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}