{
 "title": "Saga Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalTxns\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total accounts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalAccounts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total addresses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalAddresses\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalBlocks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total native coin transfers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalNativeCoinTransfers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total tokens (non native)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalTokens\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total contracts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalContracts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total verified contracts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(saga_stats{metric=\"totalVerifiedContracts\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chainlets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (database) (saga_stats))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}