{
 "title": "SPC Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", namespace=\"sagasrv-spc\", pod=~\"spc-.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cometbft metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{app=~\"spc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{app=\"spc\"}",
     "legendFormat": "Total TXs"
    }
   ]
  },
  {
   "title": "Validator set",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cometbft_consensus_validators{app=\"spc\"})",
     "legendFormat": "Total TXs"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{app=~\"spc\"}",
     "legendFormat": "Number"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Validator Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "cosmos_validators_status{app=\"spc-cosmos-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jailed status",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "cosmos_validators_jailed{app=\"spc-cosmos-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total jailed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_jailed{app=\"spc-cosmos-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Block size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{app=~\"spc\"}",
     "legendFormat": "Block size"
    }
   ]
  },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "cometbft_mempool_size{app=\"spc\"}",
     "legendFormat": "Mempool size"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=\"$pod\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=\"$pod\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", pod=\"$pod\", resource=\"memory\"}\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=\"$pod\", resource=\"memory\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Receive bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_reads_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "Reads"
    },
    {
     "expr": "ceil(sum by(pod) (rate(container_fs_writes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", container!=\"\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}