{
 "title": "Validators / Overview by chainlet",
 "description": "Stats of a Cosmos validators set",
 "tags": [
  "cosmos",
  "blockchain"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_validators_status, chainId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "total validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_status{chainId=\"$chain_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_status{chainId=\"$chain_id\"} == 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "inactive validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_status{chainId=\"$chain_id\"} != 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jailed validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_jailed{chainId=\"$chain_id\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "delegator shares",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_delegator_shares{chainId=\"$chain_id\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "commissions",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validators_commission{chainId=\"$chain_id\"} * 100",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "min self delegation",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validators_min_self_delegation{chainId=\"$chain_id\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "bound status",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validators_status{chainId=\"$chain_id\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "validator shares",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_delegator_shares{chainId=\"$chain_id\"}",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "tokens",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validators_tokens{chainId=\"$chain_id\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "jailed",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validators_jailed{chainId=\"$chain_id\"} == 1",
     "legendFormat": "%"
    }
   ]
  }
 ]
}