{
 "title": "Validators / Jailed",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jailed chainlets by cluster",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validators_jailed) by (moniker)",
     "legendFormat": "{{moniker}}"
    }
   ]
  },
  {
   "title": "Chainlets with jailed validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (chainId) (cosmos_validators_jailed == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jailed validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cosmos_validators_jailed)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jailed validators",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cosmos_validators_jailed == 1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jailed chainlets by cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(cosmos_validators_jailed) by (moniker)",
     "legendFormat": "{{moniker}}"
    }
   ]
  }
 ]
}